{% set name = "pox" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: f08b5453edf94fd6fdb28e043658cdd6151d5fd8384066a24fad8d4bd7e637c0

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - pox

about:
  home: http://trac.mystic.cacr.caltech.edu/project/pathos/wiki.html
  license: BSD 3-Clause
  license_file: LICENSE
  summary: utilities for filesystem exploration and automated builds

extra:
  recipe-maintainers:
    - jschueller
