{% set name = "pox" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e825225297638d6e3d49415f8cfb65407a5d15e56f2fb7fe9d9b9e3050c65ee1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - pip
    - python =2.7|>=3.6
  run:
    - python =2.7|>=3.6

test:
  imports:
    - pox

about:
  home: https://github.com/uqfoundation/pox
  license: BSD-3-Clause
  license_file: LICENSE
  summary: utilities for filesystem exploration and automated builds

extra:
  recipe-maintainers:
    - jschueller
    - synapticarbors
