{% set name = "pox" %}
{% set version = "0.2.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2b53fbdf02596240483dc2cb94f94cc21252ad1b1858c7b1c151afeec9022cc8

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - pox

about:
  home: http://trac.mystic.cacr.caltech.edu/project/pathos/wiki.html
  license: BSD 3-Clause
  license_file: LICENSE
  summary: utilities for filesystem exploration and automated builds

extra:
  recipe-maintainers:
    - jschueller
