travis:
  secure:
    BINSTAR_TOKEN: s28DC7U0KyE3Gkdh8Y/4TM7Av7kW3aqipv+JTFOiJ8LENCMP64bxjrlXR4rk43CXi1Nkhc3jLniRtCZUDBWgi5mE9rlC2UjCOuuqIrQ8grsL8KRSZtLReyHSRHR6uvnTi2TQkMu2bPnW+mTVnvi25ylZgMv9Pm4yDFfZzxEYBP2aMU25XqE2KAh+IJij4NjqZKINOIAynDREb6qCvgkzybeZ+ud3fJzD35ZrhUM031sieeV4Ri9ZNjRanwYtqPbgwJfdQ0wjNHayhUrd9sCKA38QfPeKASMG9tIM4FWSZBXH2dlu3u+uVkgI2k8kmujbuDaO5n2OhvzqXm9RbchUFUTlnFCsa1ae1jd4Br3EG0z/W1gS5jKdgK3pwFgyYT7ER/saZ5ODsDDTTbka2P2GeG4M/L594f5afMQpReEP5kHSEwvNJZJgOZnY9SmBCeHXwExqq9VyQVdur5pSVM5gG3YAdmSjJ6L6b3yoDDDA4Hf6THykvdNWikmTyzeXfvlqsF9f3C4m+DRy4JPn3vwCPZqg7B+b1PPfE317mT7nju4qh7yByW5KDVfEKwl54mjK/0EqJadmAPMFw6rH4uzTiwa0Baugz9vDz/6MPbxvG2tVSaG1bx6VvgXz7iGYH82TBjuOdlg7cOnhR5ivWicHk+YuQkNwGV2PJELWicR6veE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
