travis:
  secure:
    BINSTAR_TOKEN: oELRE1Vd2odyHyE0pOsf77H0Mm3mRJs/cQ8winWRxc6ybkqvHDAlF0HTWqhv8GfzuYm41Wpw9fSgfpY2XvXeAeXrWM/xV1OIQCStsm+128EC9XdHeUCHpavxuGzG4Qvkj1HZalj3x3FB7D08hgTZRQMwAPtY3O2KGw61W1oumtugILKMG7rAnStpBqfIXN5P/KIWAbF3xtYaBAB6KcWmGkiUT+A/C730BP6casD4m1mAq/Yhv2vuFjk6QQ0t1s3TxMJVnZon8xf4EKFMQ/9x9sgV+LVxBJuXqKuD5uv6mlt5j1eaIeZbt6U7/0dX/NhH8x7eJD/+oJn/JiMeVu5Z213d6a0qwEL79aK96Co6aJpo5Lh/hmxpQno/GDQu6a4d0AEmF0k9PvafSMGQvza5TUNU+L8xRs3dqPZ7zw85IWLrQ5/I47Nz8LVuS8ZcirC8Z+84RxrDsVZdN2vaITO/sZo+YMVA1E+lFYBKlUw459dPlk1Ypvwj+poG3whfT9Cq4ljYSeZ79kIBTetsIK49gXHCWOlsJppWrgDZ/4MVv0L2h9aneuuAyGbDX4sBoynuKxBo1INuGVkMg0gqwl4pe3lnNVzqfQWVD2i2RqTaI90ewI9TfkpgiwIHMV4YPUqWB667OKu0InqoJMoDINrxw3CBLF0/KASFGn8f+kt3oyk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
