travis:
  secure:
    BINSTAR_TOKEN: RlNgCCOpg9/Qxdpnwby0Hk44R5FQJqY4JKJOFtzA9RkNtNwflQUHSl2N7qpmxKJ67ZbZ/VZJgM9HtYe3trOSUfrZQChUTZ+Pm0u4ytu7V3xNRECXN/4HkCF91xBbNFMNuoGkUuz4Og51e2yFzWRCITGoaDiCFbPuEK7JqkwkPF5+mVfvQ/QtamXbzx4w1dimFF6W5jfvjCNu7EsRK+3fF15kzwVbRxNLcOJphmVv/hqpqgTh0UAA64jSMianXhoCvZW7+BDGh3aC9mmFoqOMIurPvn13wRust9fYS/d43N5Yu/jtwwOO+OHUhy+jQwV7Eh/3XXPcOJU4p1+vTuiAI2h0Cvq5w8JNgcQsdCLrSulLqn5DQwTNqmt0hLuYFjMP8cBK6bv3qpBQnqFJ8p4E60kr3HqXnS2I6k/zpmytd923LK3Ir7AdMzgu0AaZLqfLJRF3hIJhqRfp2T/Kkk/zSoVXKE4/lSb8rFTydr98VIoTdjynis16R27RmZQHrE/RwRqAFSx8FxZ4bWtFt2vczuRvl3vlS8IQCn8SkADeeXYT9azIzwBnWSbJZaRVRNigy+kijjZeGJ2kYYFdzfKVZa0Glo6p1QE2u9re3Z2O8Gtpdp4UOzIyaqXr0ZndtgZ3gKMebh7DpnCPR4A93ks5xnAksAiMJgtLAbSbkV8mmL4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
